In [6]:
import numpy as np
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [11]:
np.eye((2))

array([[1., 0.],
       [0., 1.]])

In [12]:
np.arange(0,100,11)

array([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [14]:
np.linspace(0,100,10)#equally spaced

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [3]:

import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]] ,dtype=int)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
arr.shape

(3, 4)

In [22]:
arr.size

12

In [26]:
arr.dtype

dtype('int64')

In [28]:
np.ndim

<function ndim at 0x00000225E19DAAB0>

In [4]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [5]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
arr.flatten() #it will make the 2d to 1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])