In [2]:
import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
np.sum(arr,axis=0) #sum of the row

array([12, 15, 18])

In [3]:
np.sum(arr,axis=1) #sum of colom

array([ 6, 15, 24])

In [4]:
arr[0]

array([1, 2, 3])

In [5]:
arr[0,1]

np.int64(2)

In [8]:
print(arr[0,0])

1


In [9]:
print(arr[0:2, 1:3])  # Extracts first 2 rows and last 2 columns

[[2 3]
 [5 6]]


In [17]:
print(arr[1:3, 1:3])

[[5 6]
 [8 9]]


In [22]:
print(arr[2:3,2:3])

[[9]]


In [24]:
print(arr[1:3,0:2])

[[4 5]
 [7 8]]


In [3]:
flatted=arr.flatten()

In [7]:
flatted

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
flatted[8]

np.int64(9)

In [10]:
index=[1,3,5]
print(arr[index])

IndexError: index 3 is out of bounds for axis 0 with size 3

In [11]:
import numpy as np

# Example array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

# Indices you want
index = [1, 3, 5]

# Get elements at positions 1, 3, 5
print(arr[index])


[20 40 60]


In [14]:
import numpy as np

# Example array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

con=arr>30#it will like the index slicing the if else statements which stored in the con and acess with condithin
print(arr[con])


[40 50 60 70 80]


In [2]:
import numpy as np

# Create a 3D array
arr = np.array([
    [[1, 2, 3], [4, 5, 6]],     # First 2D array (layer 0)
    [[7, 8, 9], [10, 11, 12]]   # Second 2D array (layer 1)
])

print(arr)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
print(arr[1,:,:])

[[ 7  8  9]
 [10 11 12]]
